-- PriceTrack MVP - schema server-only.
-- Pode ser usado em um projeto Supabase dedicado ou junto de outros apps sem colisão de nomes.

create extension if not exists pgcrypto;

create table if not exists public.pricetrack_credentials (
  marketplace text primary key,
  access_token_enc text not null,
  refresh_token_enc text not null,
  expires_at timestamptz not null,
  external_user_id bigint,
  updated_at timestamptz not null default now()
);

create table if not exists public.pricetrack_monitors (
  id uuid primary key default gen_random_uuid(),
  marketplace text not null check (marketplace in ('mercadolivre')),
  item_id text not null unique,
  title text not null,
  product_url text not null,
  image_url text,
  currency_id text not null default 'BRL',
  current_price numeric(12,2) not null check (current_price > 0),
  reference_price numeric(12,2) not null check (reference_price > 0),
  lowest_price numeric(12,2) not null check (lowest_price > 0),
  highest_price numeric(12,2) not null check (highest_price > 0),
  available_quantity integer,
  marketplace_status text,
  alert_threshold_percent numeric(7,2) not null default 15,
  active boolean not null default true,
  last_checked_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pricetrack_price_snapshots (
  id bigint generated by default as identity primary key,
  monitor_id uuid not null references public.pricetrack_monitors(id) on delete cascade,
  price numeric(12,2) not null check (price > 0),
  original_price numeric(12,2),
  available_quantity integer,
  captured_at timestamptz not null default now()
);

create table if not exists public.pricetrack_alerts (
  id uuid primary key default gen_random_uuid(),
  monitor_id uuid not null references public.pricetrack_monitors(id) on delete cascade,
  snapshot_id bigint references public.pricetrack_price_snapshots(id) on delete set null,
  signal text not null check (signal in ('deal','hot','possible_bug')),
  discount_percent numeric(7,2) not null,
  score integer not null check (score between 0 and 100),
  price numeric(12,2) not null,
  reference_price numeric(12,2) not null,
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists pricetrack_snapshots_monitor_time_idx on public.pricetrack_price_snapshots(monitor_id, captured_at desc);
create index if not exists pricetrack_alerts_monitor_time_idx on public.pricetrack_alerts(monitor_id, created_at desc);
create index if not exists pricetrack_monitors_active_check_idx on public.pricetrack_monitors(active, last_checked_at);

alter table public.pricetrack_credentials enable row level security;
alter table public.pricetrack_monitors enable row level security;
alter table public.pricetrack_price_snapshots enable row level security;
alter table public.pricetrack_alerts enable row level security;

-- O navegador nunca acessa as tabelas diretamente neste MVP.
revoke all on table public.pricetrack_credentials from anon, authenticated;
revoke all on table public.pricetrack_monitors from anon, authenticated;
revoke all on table public.pricetrack_price_snapshots from anon, authenticated;
revoke all on table public.pricetrack_alerts from anon, authenticated;

grant select, insert, update, delete on table public.pricetrack_credentials to service_role;
grant select, insert, update, delete on table public.pricetrack_monitors to service_role;
grant select, insert, update, delete on table public.pricetrack_price_snapshots to service_role;
grant select, insert, update, delete on table public.pricetrack_alerts to service_role;
grant usage, select on all sequences in schema public to service_role;
