-- PriceTrack MVP schema
-- Run this in the Supabase SQL editor when a project is selected.

create extension if not exists pgcrypto;

create table if not exists public.monitors (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  marketplace text not null,
  product_url text not null,
  target_price numeric(12,2),
  reference_price numeric(12,2),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.price_snapshots (
  id bigint generated by default as identity primary key,
  monitor_id uuid not null references public.monitors(id) on delete cascade,
  price numeric(12,2) not null check (price > 0),
  availability text,
  captured_at timestamptz not null default now()
);

create table if not exists public.alerts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  monitor_id uuid not null references public.monitors(id) on delete cascade,
  snapshot_id bigint references public.price_snapshots(id) on delete set null,
  signal text not null check (signal in ('deal','hot','possible_bug')),
  discount_percent numeric(7,2) not null,
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists monitors_user_id_idx on public.monitors(user_id);
create index if not exists price_snapshots_monitor_time_idx on public.price_snapshots(monitor_id, captured_at desc);
create index if not exists alerts_user_time_idx on public.alerts(user_id, created_at desc);

alter table public.monitors enable row level security;
alter table public.price_snapshots enable row level security;
alter table public.alerts enable row level security;

grant select, insert, update, delete on table public.monitors to authenticated;
grant select on table public.price_snapshots to authenticated;
grant select, update on table public.alerts to authenticated;

create policy "users manage own monitors"
on public.monitors
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "users read own snapshots"
on public.price_snapshots
for select
to authenticated
using (
  exists (
    select 1 from public.monitors m
    where m.id = monitor_id and m.user_id = (select auth.uid())
  )
);

create policy "users read own alerts"
on public.alerts
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "users update own alerts"
on public.alerts
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
